"""
PDF GENERATION UTILITIES - JurisLink V4.0 (Secure)
Provides secure PDF generation and static file serving for case documents.
"""
import os
from pathlib import Path
from datetime import datetime
import logging
from fpdf import FPDF
from shared_lib.utils import get_secure_storage_path

class CaseBriefPDF(FPDF):
    """Professional Case Brief PDF template (V4.0 Design)."""
    
    def __init__(self, case_id: str):
        super().__init__()
        self.case_id = case_id
        
    def header(self):
        self.set_font('Arial', 'B', 14)
        self.set_fill_color(15, 23, 42)  # Slate 900
        self.set_text_color(255, 255, 255)
        self.cell(0, 15, 'JURISLINK INTELLIGENCE REPORT', 0, 1, 'C', True)
        self.set_text_color(0, 0, 0)
        self.set_font('Arial', 'B', 10)
        self.ln(5)
        self.cell(0, 6, f'CASE ID: {self.case_id}', 0, 1, 'R')
        self.line(10, 35, 200, 35)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(100, 116, 139) # Slate 500
        self.cell(0, 10, f'CONFIDENTIAL • Generated by JurisLink AI • Page {self.page_no()}', 0, 0, 'C')

def clean_text_for_pdf(text: str) -> str:
    """Replace problematic characters for PDF encoding."""
    if not text:
        return ""
    # Replace common smart quotes and em-dashes
    replacements = {
        '\u2018': "'", '\u2019': "'", '\u201c': '"', '\u201d': '"',
        '\u2013': '-', '\u2014': '--', '\u2026': '...'
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text.encode('latin-1', 'replace').decode('latin-1')

def generate_case_brief_pdf(user_id: str, case_id: str, facts: dict, strategy: str = None, research: dict = None) -> str:
    """
    Generate a secure Case Brief PDF.
    """
    if not user_id:
        raise ValueError("Security Violation: Missing user_id")

    storage_path = get_secure_storage_path(user_id, case_id)
    filename = "case_brief.pdf" # Standardized name inside protected folder
    file_path = storage_path / filename
    
    pdf = CaseBriefPDF(case_id)
    pdf.add_page()
    
    # Metadata
    pdf.set_font("Arial", '', 10)
    pdf.cell(0, 6, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1)
    pdf.ln(5)
    
    # Helper for sections
    def add_section(title, content):
        pdf.set_font("Arial", 'B', 12)
        pdf.set_fill_color(241, 245, 249) # Slate 100
        pdf.cell(0, 8, title.upper(), 0, 1, 'L', True)
        pdf.ln(3)
        pdf.set_font("Arial", '', 11)
        pdf.multi_cell(0, 6, clean_text_for_pdf(content))
        pdf.ln(6)

    # 1. Facts
    fact_text = ""
    if facts:
        for k, v in facts.items():
            if k != 'status' and v:
                fact_text += f"{k.replace('_', ' ').title()}: {v}\n"
    else:
        fact_text = "No facts recorded."
    add_section("Key Facts", fact_text)

    # 2. Strategy
    if strategy:
        add_section("Legal Strategy", strategy)

    # 3. Research
    if research:
        res_text = ""
        if isinstance(research, dict):
            for k, v in research.items():
                res_text += f"[{k}]: {str(v)[:1000]}...\n\n"
        else:
            res_text = str(research)[:3000]
        add_section("Research Notes", res_text)
    
    pdf.output(str(file_path))
    return str(file_path)

def get_existing_pdf_path(user_id: str, case_id: str) -> str:
    """Get path to existing PDF if authorized."""
    try:
        storage_path = get_secure_storage_path(user_id, case_id)
        file_path = storage_path / "case_brief.pdf"
        if file_path.exists():
            return str(file_path)
    except Exception:
        pass
    return None

def delete_case_pdf(user_id: str, case_id: str) -> bool:
    """Securely delete case file."""
    try:
        path_str = get_existing_pdf_path(user_id, case_id)
        if path_str:
            Path(path_str).unlink()
            return True
    except Exception:
        pass
    return False
